Prevent pause menu engine halt
qbcore-fivem/qb-hud pull request #108
Opened 2022-01-20 06:25 UTC by helenclarko

If the toggle engine key is set to mouse wheel, this will prevent the engine stop/start when in the pause menu.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

2022-01-20 16:02 UTC, jnccloud requested changes
Please update this to use the locale system.

2022-01-21 03:02 UTC, helenclarko commented
Sorry about that, corrected in latest commit.

2022-01-28 18:43 UTC, JajarGaming approved these changes

2022-03-12 04:53 UTC, GhzGarage commented
@loljoshie

2022-12-09 16:48 UTC, Z3rio commented
No longer valid PR (because of it being outdated)

2022-12-09 16:48 UTC, closed without merging